"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var message = 'Wlecome back';
console.log(message);
var x = 10;
var y = 20;
var sum;
var title = 'TypeScript Tutorial';
var isBeginner = true;
var total = 0;
var name = 'Vishwas';
var sentence = " My name is ".concat(name, "\nI am a beginner in Typescript");
console.log(sentence);
var n = null;
var u = undefined;
var isNew = null;
var myName = undefined;
