"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var message = 'Wlecome back';
console.log(message);
var x = 10;
var y = 20;
var sum;
var title = 'TypeScript Tutorial';
var isBeginner = true;
var total = 0;
var name = 'Vishwas';
var sentence = " My name is ".concat(name, "\nI am a beginner in Typescript");
console.log(sentence);
var n = null;
var u = undefined;
var list1 = [1, 2, 3];
var list2 = [1, 2, 3];
var person1 = ['Chris', 22];
var Color;
(function (Color) {
    Color[Color["Red"] = 5] = "Red";
    Color[Color["Green"] = 6] = "Green";
    Color[Color["Blue"] = 7] = "Blue";
})(Color || (Color = {}));
;
var c = Color.Green;
console.log(c);
